### ISSUE TITLE
How do I decrypt the encrypted value? 

### ISSUE THREAD

**Issue by Zlate87** [googlesamples/android-ConfirmCredential#4]
The sample only shows how to encrypt the data, but what steps should I use to decrypt?

I created a question of stackoverflow, but no luck so far: http://stackoverflow.com/questions/33214469/issue-while-using-android-fingerprint-iv-required-when-decrypting-use-ivparame

Can someone help with this?

**Comment by thagikura** [comment]
Hi,

You can decrypt the data by like following:
As mentioned in the [issue on FingerprintDialog sample](https://github.com/googlesamples/android-FingerprintDialog/issues/10), you can get the IV by `Cipher.getIV()` from the Cipher object when you used for encrypting the data.

You need to pass the third parameter in the `Cipher.init` method to decrpyt the data.

```
            cipher.init(Cipher.DECRYPT_MODE, secretKey, new IvParameterSpec(encryptCipher.getIV()));
            byte[] decryptedBytes = cipher.doFinal(encryptedBytes);
```

**Comment by Zlate87** [comment]
Thanks @thagikura 

Using the IV from the encryption solved the issue.

I created a sample application that will do encryption/decryption, if anyone is interested it is available here: https://github.com/Zlate87/android-fingerprint-example

Regards,
Zlatko
