### ISSUE TITLE
On MiA1 running Android O, keyguard unlock runs into a loop and never exits

### ISSUE THREAD

**Issue by Gopinathp** [googlesamples/android-ConfirmCredential#6]
On MiA1 running Android O, the request key guard action, runs in a loop and is not able to confirm credential. tryEncrypt() always fails with UserNotAuthenticatedException.

I'm not able to use this confirm credentials option for some sensitive features of the app.

**Comment by Gutyn** [comment]
This is the exact problem I have too @Gopinathp. I've come to the conclusion that this is a Keystore bug on some devices.

**Comment by Kieun** [comment]
It seems that when we use PIN, password or pattern, there is no problem. But in case of using other verification methods such as fingerprint, iris or face, during accessing the keys, UserNotAuthenticationException is always thrown.

**Comment by NasH5169** [comment]
Same on Huawei ALE L21 (P8 Lite) / Android 6.0

The Cipher.init always crashes with UserNotAuthenticatedException

**Comment by ashishb** [comment]
Same issue on `One Plus 5T`

```
Manufacturer: OnePlus
Model: ONEPLUS A5010 (OnePlus 5T)
Release: 8.1.0
SDK version: 27
CPU: arm64-v8a
```

**Comment by ashishb** [comment]
Apparently, rebooting the phone fixes the issue for me.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
